org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.configuration-cache=true
parchmentMinecraftVersion=1.21.11
parchmentMappingsVersion=2025.12.21-nightly-SNAPSHOT
minecraftVersion=1.21.1
minecraftVersionRange=[1.21.1]
neoVersion=21.1.219
neoVersionRange=[21.1,)
loaderVersionRange=[1,)
loaderName=javafml

modId=servertools
modName=ServerTools
modLicense=All Rights Reserved
modVersion=1.0.0
modGroupId=dev.fatyoshi.thatguyjustin.servertools
modAuthors=ThatRandoJustin, McIsTheLimit, Nadie__
modDescription=Add discord chat support, and automated restarts.

# dependencies
jacksonVersion=2.19.1
kotlinCoroutinesVersion=1.8.1
kotlinSerializationVersion=1.7.3
jdaVersion=6.3.0
jdaKTXVersion=0.14.0
trove4jVersion=3.0.3
slf4jVersion=2.0.9
discordWebhookVersion=0.8.4
tinkVersion=1.10.0
adventurePlatformVersion=6.0.1
admiralVersion=0.4.10
okhttpVersion=4.10.0
okioVersion=3.0.0
nvWebSocketClientVersion=2.14
ccCollections4Version=4.5.0